Guard against the lack of local variables
POSIX sh doesn't have local variables so there is risk of any method
call override variables that would be "local" in other languages. To
avoid future hard to debug problems related to this, certain rules have
been added about which methods can be called from others. Basically
helper methods can be called from anywhere and only call other helpers.
These methods' vars also all start with an underscore. Callers to pkg_
methods have to be careful and not access local variables after a method
call. And nothing should call action_ methods (besides the initial
switch)

Some methods were moved/renamed to make the rules more straight forward

diff --git a/pkgmanager b/pkgmanager
--- a/pkgmanager
+++ b/pkgmanager
@@ -30,11 +30,14 @@ PKGMAN_SOURCE_FIX_FILE=${PKGMAN_SOURCE_FIX_FILE:-"/etc/$PKGMAN_NAME/source_fix"}
 
 
 ############## General helpers
+# These methods may read global variables and all their local vairables should
+# start with '_'
+# They may only call methods in this category
+
 die() {
     echo "Error: $*" >&2
     exit 2
 }
-
 
 info() {
     echo "$@"
@@ -60,29 +63,26 @@ download_file() {
     $PKGMAN_DOWNLOAD_CMD "$1"
 }
 
-# Takes a sources file
 download_sources() {
-    pkg="$1"
-    dest=$PKGMAN_SOURCE_CACHE_DIR/$pkg
-    mkdir -p "$dest"
-    while read -r url dir; do
-
-        filename="$(basename "$url")"
-        if [ -n "$dir" ]; then
-            mkdir -p "$dir"
-            filename="$dir/$filename"
+    _dest="$PKGMAN_SOURCE_CACHE_DIR/$1"
+    mkdir -p "$_dest"
+    while read -r _url _dir; do
+        _filename="$(basename "$_url")"
+        if [ -n "$_dir" ]; then
+            mkdir -p "$_dir"
+            _filename="$_dir/$_filename"
         fi
-        fullpath="$dest/$filename"
-        debug "checking cache for $url"
-        if [ ! -e "$fullpath" ]; then
-            debug "downloading $url"
-            download_file "$url" > "$fullpath.tmp"
-            mv "$fullpath.tmp" "$fullpath"
+        _fullpath="$_dest/$_filename"
+        debug "checking cache for $_url"
+        if [ ! -e "$_fullpath" ]; then
+            debug "downloading $_url"
+            download_file "$_url" > "$_fullpath.tmp"
+            mv "$_fullpath.tmp" "$_fullpath"
         fi
-        if [ -z "$dir" ]; then
-            echo "$fullpath" "."
+        if [ -z "$_dir" ]; then
+            echo "$_fullpath" "."
         else
-            echo "$fullpath" "$dir"
+            echo "$_fullpath" "$_dir"
         fi
     done
 }
@@ -93,54 +93,58 @@ get_default_pkg() {
 
 extract() {
     debug "Extracting $*"
-    fullpath=$1
-    destdir=$2
-    [ -n "$fullpath" ] && [ -n "$destdir" ]
-    case $fullpath in
+    _fullpath=$1
+    _destdir=$2
+    [ -n "$_fullpath" ] && [ -n "$_destdir" ]
+    case $_fullpath in
         *.tar|*.tar.*)
-            decompress "$fullpath" | tar -xf - -C "$destdir"
+            decompress "$_fullpath" | tar -xf - -C "$_destdir"
         ;;
         *.zip)
-            unzip "$fullpath" -d "$destdir"
+            unzip "$_fullpath" -d "$_destdir"
         ;;
         *)
-            cp "$fullpath" "$destdir"
+            cp "$_fullpath" "$_destdir"
         ;;
     esac
 }
 
 for_each_in_path() {
-    dir=$2
+    _dir=$2
     # shellcheck disable=2086
     { IFS=:; set -- ${1:-"$PKGMAN_PATH"}; unset IFS; }
-    for path ; do
-        [ -e "$path/$dir" ] || continue
-        echo "$path/$dir"
+    for _path ; do
+        [ -e "$_path/$_dir" ] || continue
+        echo "$_path/$_dir"
     done
 }
 
-# hooks
 run_hook(){
     export TYPE="$1"
     export PKG="$2"
     debug "Running hook '$TYPE'"
-    for hook in $(for_each_in_path "$PKGMAN_HOOK_PATH") ; do
-        for script in "$hook/"*.sh; do
-            if [ -r "$script" ]; then
-                . "$script"
+    for _hook in $(for_each_in_path "$PKGMAN_HOOK_PATH") ; do
+        for _script in "$_hook/"*.sh; do
+            if [ -r "$_script" ]; then
+                . "$_script"
             fi
         done
     done
 }
 
-############## Read state of packages in repo
+############## Read state of packages
+# These methods all start with "pkg_" + read/get/is/gen etc.
+# Basically anything that doesn't touching disk or other state manipulation
+# These methods just read state and have the same restriction has the above helpers
+# int that local variables must start with _
+
 pkg_read_version() {
-    path=$1
-    full_version=${2:-0}
-    read -r _v _r<"$path/version"
-    if [ "$full_version" -eq 0 ]; then
+    _path=$1
+    _full_version=${2:-0}
+    read -r _v _r<"$_path/version"
+    if [ "$_full_version" -eq 0 ]; then
         echo "$_v"
-    elif [ "$full_version" -eq 1 ]; then
+    elif [ "$_full_version" -eq 1 ]; then
         echo "${_v}_$_r"
     else
         echo "$_v $_r"
@@ -155,7 +159,65 @@ pkg_read_raw_version() {
     pkg_read_version "$1" 2
 }
 
-# Searches "$PKGMAN_PATH" for the specified package
+# Reads raw sources file removing blank lines and comments
+pkg_read_sources() {
+    [ -e "$1/sources" ] && sed '/^#/d; /^$/d' "$1/sources"
+}
+
+# Outputs the built tar; fails if package isn't built
+pkg_is_built() {
+    _pkg=$1
+    _path=$2
+    _v="$(pkg_read_full_version "$_path")"
+    _archive="$PKGMAN_BUILD_CACHE_DIR/${_pkg}_${_v}.tar"
+    [ -e "$_archive" ] || return 2
+    echo "$_archive"
+}
+
+# Outputs the built tar; exits if package isn't built
+pkg_get_built() {
+    pkg_is_built "$1" "$2" || die "Package not built"
+}
+
+# Returns success if packages is installed
+pkg_is_installed() {
+    [ -d "$PKGMAN_METADATA_INSTALL_DIR/$1" ]
+}
+
+# Outputs the version of the installed package if package is installed
+pkg_get_installed_version() {
+    [ -e "$PKGMAN_METADATA_INSTALL_DIR/$1/version" ] &&
+        pkg_read_raw_version "$PKGMAN_METADATA_INSTALL_DIR/$1/"
+}
+
+# Outputs a manifest file for the given directory
+pkg_gen_manifest() {
+    _dir=$1
+    find "$_dir" | sed -e "s:$_dir::" -e '/^$/d' | sort
+}
+
+################ Business logic
+# These methods can call anything in the above layer and within this layer
+# However, if a method in this layer is called, it should assume
+# that all of its local variables are invalidated
+
+# Searches for the matching extensions in PATH
+pkg_find_ext() {
+    name=$1
+    for_each_in_path "$PATH" | while read -r path; do
+        if [ -x "$path/$name" ]; then
+            printf "%s\t%s\n" "$name" "$path/$name"
+            return
+        else
+            for executable in "$path/$name"*; do
+                if [ -x "$executable" ]; then
+                    printf "%s\t%s\n" "${executable#"$path/"}" "$executable"
+                fi
+            done
+        fi
+    done
+}
+# Searches "$PKGMAN_PATH" for the specified package by exact name
 pkg_find() {
     target=$1
     pkg="$(for_each_in_path "$PKGMAN_PATH" "$target" | head -n1)"
@@ -163,6 +225,7 @@ pkg_find() {
     echo "$pkg"
 }
 
+# Like find but accepts wildcards
 pkg_search() {
     target=$1
     for_each_in_path "$PKGMAN_PATH" | while read -r path; do
@@ -170,10 +233,6 @@ pkg_search() {
             [ -d "$pkg" ] && echo "$pkg"
         done
     done | grep "$target"
-}
-
-pkg_read_sources() {
-    [ -e "$1/sources" ] && sed '/^#/d; /^$/d' "$1/sources"
 }
 
 _pkg_find_nested_deps() {
@@ -216,37 +275,19 @@ pkg_find_deps() {
     pkg_find_nested_deps "$1" "$2" 0 0
 }
 
-############## Read PKGMANGAGER specific state
-
-# Outputs the built tar; fails if package isn't built
-pkg_is_built() {
-    _pkg=$1
-    _path=$2
-    _v="$(pkg_read_full_version "$_path")"
-    archive="$PKGMAN_BUILD_CACHE_DIR/${_pkg}_${_v}.tar"
-    [ -e "$archive" ] || return 2
-    echo "$archive"
+pkg_get_build_order() {
+    {
+        if [ $# -eq 0 ]; then
+            while read -r pkg; do
+                echo "$(pkg_find_nested_deps "$pkg" | sort -u | wc -l) $pkg"
+            done
+        else
+            for pkg do
+                echo "$(pkg_find_nested_deps "$pkg" | sort -u | wc -l) $pkg"
+            done
+        fi
+    } | sort -n | cut -d" " -f2
 }
-
-# Outputs the built tar; exits if package isn't built
-pkg_get_built() {
-    pkg_is_built "$1" "$2" || die "Package not built"
-}
-
-# Returns success if packages is installed
-pkg_is_installed() {
-    [ -d "$PKGMAN_METADATA_INSTALL_DIR/$1" ]
-}
-
-# Outputs the version of the installed package if package is installed
-pkg_get_installed_version() {
-    [ -e "$PKGMAN_METADATA_INSTALL_DIR/$1/version" ] && {
-        read -r v r < "$PKGMAN_METADATA_INSTALL_DIR/$1/version"
-        echo "${v}_${r}"
-    }
-}
-
-# Business logic
 
 pkg_download() {
     pkg=$1
@@ -270,8 +311,12 @@ pkg_extract_sources() {
     [ -d "$path" ]
     version=$(pkg_read_version "$path")
 
+    # Download in subshell to avoid risk of method modifing our
+    # local vars
+    (
     # Download sources first to verify we can download them
     pkg_download "$pkg" "$path" "$version" >/dev/null
+    )
 
     mkdir -p "$dest"
 
@@ -280,7 +325,9 @@ pkg_extract_sources() {
         git clone "${rpath#git+}" "$dest/$dirname"
     done
 
-    pkg_download "$pkg" "$path" "$version" | while read -r fullpath dirname; do
+    # Download in subshell to avoid risk of method modifing our
+    # local vars
+    ( pkg_download "$pkg" "$path" "$version" ) | while read -r fullpath dirname; do
         mkdir -p "$dest/$dirname"
         tmp="$path/.tmp"
         mkdir -p "$tmp"
@@ -307,26 +354,6 @@ pkg_extract_sources() {
     done
 }
 
-pkg_gen_manifest() {
-    find "$1" | sed -e "s:$1::" -e '/^$/d' | sort
-}
-
-pkg_ext() {
-    name=$1
-    for_each_in_path "$PATH" | while read -r path; do
-        if [ -x "$path/$name" ]; then
-            printf "%s\t%s\n" "$name" "$path/$name"
-            return
-        else
-            for executable in "$path/$name"*; do
-                if [ -x "$executable" ]; then
-                    printf "%s\t%s\n" "${executable#"$path/"}" "$executable"
-                fi
-            done
-        fi
-    done
-}
-
 pkg_build_helper() {
     pkg=$1
     path=$2
@@ -341,7 +368,8 @@ pkg_build_helper() {
     DEST_DIR="$WORKING_DIR/dest_dir"
     BUILD_DIR="$WORKING_DIR/build_dir"
     mkdir -p "$DEST_DIR"
-    pkg_extract_sources "$pkg" "$path" "$BUILD_DIR"
+    # Run in subshell to ensure validity of local variables
+    ( pkg_extract_sources "$pkg" "$path" "$BUILD_DIR" )
 
     raw_version=$(pkg_read_raw_version "$path" )
     version="$(pkg_read_full_version "$path")"
@@ -446,19 +474,19 @@ pkg_install_helper() {
 
     cd "$PKGMAN_METADATA_INSTALL_DIR/$pkg"
     run_hook post-install "$pkg"
-
 }
 
+# Installs (or reinstalls) a package
 pkg_install() {
-    pkg=$1
-    path=$2
-    info "installing $pkg"
+    info "installing $1"
 
     # ensure non-make dependencies are built
-    pkg_build_depedencies "$path" make
-    if ! pkg_is_built "$pkg" "$path" >/dev/null; then
-        pkg_build "$pkg" "$path"
+    pkg_build_depedencies "$2" make
+    if ! pkg_is_built "$1" "$2" >/dev/null; then
+        pkg_build "$1" "$2"
     fi
+    pkg=$1
+    path=$2
 
     archive="$(pkg_get_built "$pkg" "$path")"
     mkdir -p "$PKGMAN_METADATA_INSTALL_DIR"
@@ -481,6 +509,7 @@ pkg_remove_helper() {
     run_hook post-remove "$pkg"
 }
 
+# Removes an installed package
 pkg_remove() {
     pkg=$1
     [ -d "$PKGMAN_METADATA_INSTALL_DIR/$pkg" ] || die "Package not installed"
@@ -492,6 +521,7 @@ pkg_remove() {
 
 }
 
+# List all installed packages
 pkg_list_installed() {
     [ $# -eq 0 ] && set -- "$PKGMAN_METADATA_INSTALL_DIR/"*
     for path ; do
@@ -503,6 +533,7 @@ pkg_list_installed() {
     done
 }
 
+# Prints packages that whose installed version differs from repo
 pkg_determine_out_of_date() {
     pkg_list_installed | while read -r pkg v r; do
         if [ "${v}_${r}" != "$(pkg_read_full_version "$pkg")" ]; then
@@ -511,6 +542,8 @@ pkg_determine_out_of_date() {
     done
 }
 
+# Prints pkg and label for all installed packages that depend on the specified
+# package
 pkg_revdepends() {
     grep -lEs -- "^$1(\s|\$)" "$PKGMAN_METADATA_INSTALL_DIR/"*/depends | while read -r file; do
         relative_path=${file#"$PKGMAN_METADATA_INSTALL_DIR/"}
@@ -524,7 +557,11 @@ pkg_revdepends() {
     done
 }
 
+
 ############ External commands
+# See the help description for a textual representation of what each does
+# These methods should call pkg_X.
+# Nothing should call them outside of the very last switch case
 
 action_find() {
     [ $# -ne 0 ] || set -- "$(get_default_pkg)"
@@ -563,19 +600,6 @@ action_extract_sources() {
     done
 }
 
-_get_build_order() {
-    {
-        if [ $# -eq 0 ]; then
-            while read -r pkg; do
-                echo "$(pkg_find_nested_deps "$pkg" | sort -u | wc -l) $pkg"
-            done
-        else
-            for pkg do
-                echo "$(pkg_find_nested_deps "$pkg" | sort -u | wc -l) $pkg"
-            done
-        fi
-    } | sort -n | cut -d" " -f2
-}
 
 action_depends () {
     [ $# -ne 0 ] || { local_path=1 && set -- "$(get_default_pkg)"; }
@@ -600,7 +624,7 @@ action_tree () {
 action_build() {
     [ $# -ne 0 ] || { local_path=1 && set -- "$(get_default_pkg)"; }
     # shellcheck disable=2046
-    set -- $(_get_build_order "$@")
+    set -- $(pkg_get_build_order "$@")
     mkdir -p "$PKGMAN_BUILD_CACHE_DIR"
     for pkg do
         _set_pkg_path
@@ -612,9 +636,11 @@ action_export() {
     [ $# -ne 0 ] || { local_path=1 && set -- "$(get_default_pkg)"; }
     for pkg do
         _set_pkg_path
+        (
         if ! pkg_is_built "$pkg" "$path" >/dev/null; then
             pkg_build "$pkg" "$path"
         fi
+        )
         archive="$(pkg_get_built "$pkg" "$path")"
         cp "$archive" "${PKG_DESTDIR:-.}/"
     done
@@ -630,7 +656,7 @@ action_install() {
 }
 
 action_outdated() {
-    pkg_determine_out_of_date | _get_build_order
+    pkg_determine_out_of_date | pkg_get_build_order
 }
 
 action_fetch() {
@@ -653,9 +679,11 @@ action_revdepends() {
 action_remove() {
     [ $# -ne 0 ] || set -- "$(get_default_pkg)"
     for pkg do
+        (
         if [ "$PKGMAN_FORCE" -eq 0 ] && pkg_revdepends "$pkg" | grep -q -v "make"; then
             die "$pkg has dependents"
         fi
+        )
         pkg_remove "$pkg"
     done
 }
@@ -681,10 +709,10 @@ action_list() {
 
 action_list_ext() {
     if [ $# -eq 0 ]; then
-        pkg_ext pkgmanager- | sort -u -k1
+        pkg_find_ext pkgmanager- | sort -u -k1
     else
         for name;do
-            pkg_ext "pkgmanager-$name" | sort -u -k1
+            pkg_find_ext "pkgmanager-$name" | sort -u -k1
         done
     fi
 }
@@ -692,9 +720,8 @@ action_list_ext() {
 action_ext() {
     name="pkgmanager-$1"
     shift
-    path=$(pkg_ext "$name" | head -n1 | cut -f1)
+    path=$(pkg_find_ext "$name" | head -n1 | cut -f1)
     [ -n "$path" ]
-    debug "Using $path"
     exec $path "$@"
 }
 
